#!/usr/bin/env bash

STATE="$HOME/.local/state/$1"
REPEAT=-1
SINK="alsa_output.pci-0000_00_1f.3.analog-stereo" # Speakers

handleSIGINT() 
{
    printf "\nSIGINT Recieved! Exiting...\n"
    exit 0
}

[ -z $1 ] && \
    echo "Please provide /dev/tty device e.g. /dev/ttyACM0" && \
    exit 0

trap handleSIGINT SIGINT

inotifywait -mq -e modify --format '%w%f' "$STATE" | while read -r FILE; do   

    if read -r LINE < "$FILE"; then
        continue
    fi

    if [[ ! "$LINE" =~ ^([0-9]+):([0-9]+)$ ]]; then
        sleep 0.05
        continue
    fi

    ID="${BASH_REMATCH[1]}"
    KNOB="${BASH_REMATCH[2]}"

    PERCENT=$(( KNOB * 100/1023 ))

    if [[ "${REPEAT[$ID]}" == "$PERCENT" ]]; then
        continue
    fi

    case "$ID" in
        14)
            pactl set-sink-volume "$SINK" "${PERCENT}%" && \
                echo "Pot 1: Volume = ${PERCENT}%"
            ;;
        20)
            echo "Pot 2 moved → ${PERCENT}%"
            # you could control bass, EQ, another sink, etc.
            ;;
        *)
            echo "Unknown pot ID ${ID} = ${PERCENT}%"
            ;;
    esac

    REPEAT[$ID]=$PERCENT

   
done
