#!/usr/bin/env bash

# read data from arduino and send now playing song titles
# over serial
# 
# Elizabeth Lewis

handleSIGINT() 
{
    printf "\nSIGINT Recieved! Exiting...\n"
    exit 0
}

# Get the name of the device from the user or quit
[ -z $1 ] && \
    echo "Please provide /dev/tty device e.g. /dev/ttyACM0" && \
    exit 0

# Check for tty
if [ -t 0 ]; then
    printf "Elizabeth Swann's Arduino Serial Input/Output Service\n\n"
fi

# Initialize state file if it doesn't exist
if [ ! -e $HOME/.local/state/$1 ]; then
    > $HOME/.local/state/$1 # State file initialization
fi

FILE=$HOME/.local/state/np
PREVIOUS=""

trap handleSIGINT SIGINT

stty -F /dev/$1 -hupcl || exit 1 # Initialize the serial device and prevent reset on connect

# Main Loop
#
#
while true; do

    # Todo
    #
    # Account for memory overflow in arduino (Concat strings here)
    #
    NOWPLAYING=$(cat $FILE)

    # File is EMPTY
    if [[ -z $NOWPLAYING ]]; then
        while read -t 0.2 -r line; do
            echo $line
            echo $line | > $HOME/.local/state/$1
            break
        done < /dev/$1

    # File contains a song to be sent to the arduino
    else 

        if [[ "$NOWPLAYING" != "$PREVIOUS" ]]; then
            while read -r line; do
                printf "$NOWPLAYING" > /dev/$1
            done < $FILE

            echo "NOW PLAYING: $NOWPLAYING"
            > $FILE
            stty -F /dev/$1 -hupcl
            sleep 0.2
            PREVIOUS="$NOWPLAYING"
        fi

    fi

    sleep 0.1
done

