#!/usr/bin/env bash

STATE="$HOME/.local/state/$1"
REPEAT=-1
SINK="alsa_output.pci-0000_00_1f.3.analog-stereo" # Speakers

handleSIGINT() 
{
    printf "\nSIGINT Recieved! Exiting...\n"
    exit 0
}

[ -z $1 ] && \
    echo "Please provide /dev/tty device e.g. /dev/ttyACM0" && \
    exit 0

trap handleSIGINT SIGINT

inotifywait -mq -e modify --format '%w%f' "$STATE" | while read -r FILE; do   

    if read -r KNOB < "$FILE"; then
        continue
    fi

    PERCENT=$(( KNOB * 100/1023 ))
    [[ "$KNOB" =~ ^[0-9]+$ ]] || { sleep 0.05; continue; }

    if [[ "$PERCENT" != "$REPEAT" ]]; then

        if pactl set-sink-volume "$SINK" "${PERCENT}%"; then
            REPEAT=$PERCENT
            echo "$PERCENT%"
        fi
    fi

done
